title: realestatecassidy
tagline: all things central florida
description: "Orlando & Central Florida lifestyle, neighborhoods, and why itâ€™s the greatest place to live."
url: "https://cassidymcwhertterrealtor.github.io"

timezone: America/New_York

permalink: /blog/:year/:month/:day/:title/

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed

author:
  name: realestatecassidy

social:
  name: realestatecassidy
